### ISSUE TITLE
Couldn't run this project on Colab!

### ISSUE THREAD

**Issue by AbdulFMS** [xadrianzetx/lanefinder#3]
ERROR: Could not find a version that satisfies the requirement opencv-python==3.4.0.12 (from versions: 3.4.0.14, 3.4.2.17, 3.4.3.18, 3.4.4.19, 3.4.5.20, 3.4.6.27, 3.4.7.28, 3.4.8.29, 3.4.9.31, 3.4.9.33, 3.4.10.35, 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.14.51, 3.4.14.53, 3.4.15.55, 3.4.16.57, 3.4.16.59, 3.4.17.61, 4.0.0.21, 4.0.1.23, 4.0.1.24, 4.1.0.25, 4.1.1.26, 4.1.2.30, 4.2.0.32, 4.2.0.34, 4.3.0.36, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.2.52, 4.5.2.54, 4.5.3.56, 4.5.4.58, 4.5.4.60, 4.5.5.62)
ERROR: No matching distribution found for opencv-python==3.4.0.12
ERROR: tflite_runtime-1.14.0-cp35-cp35m-linux_armv7l.whl is not a supported wheel on this platform.
WARNING: Skipping numpy as it is not installed.
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to talk to init daemon.

then got this:

ModuleNotFoundError: No module named 'edgetpu'

**Comment by xadrianzetx** [comment]
Well, it's because this project does not really target Colab notebook as runtime. If you want to run the model over some sample images, then your best bet is just take `.tflite` model from this repo, apply [simple preprocessing](https://github.com/xadrianzetx/lanefinder/blob/master/image/processing.py#L5-L13) to the image and follow standard tflite [inference guide](https://www.tensorflow.org/api_docs/python/tf/lite/Interpreter#sample_execution).
